# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.8.0
_src_path: gh:algorandfoundation/algokit-python-template
author_email: 73354225+Therealratoshen@users.noreply.github.com
author_name: Therealratoshen
contract_name: recycless_me
deployment_language: python
preset_name: starter
project_name: recycless_me

